export interface Product {
  id: string;
  title: string;
  description: string;
  price: number;
  originalPrice?: number;
  category: string;
  emoji: string;
  gradient: string;
  badge?: string;
  rating: number;
  reviews: number;
  sales: number;
  features: string[];
  deliveryType: 'instant' | 'course' | 'saas';
}

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'Ultimate AI Prompt Pack (500+)',
    description: 'Hand-crafted prompts for ChatGPT, Claude & Midjourney. 10x your productivity instantly.',
    price: 49,
    originalPrice: 99,
    category: 'AI Tools',
    emoji: '🤖',
    gradient: 'from-blue-900/60 to-brand-900/60',
    badge: 'HOT',
    rating: 4.9,
    reviews: 1842,
    sales: 12741,
    features: ['500+ prompts', 'ChatGPT & Claude', 'Midjourney art', 'Monthly updates', 'Discord community'],
    deliveryType: 'instant',
  },
  {
    id: 'p2',
    title: 'Dropshipping Mastery Blueprint',
    description: 'Step-by-step system to build a $10k/mo dropshipping store from zero. Proven method.',
    price: 97,
    originalPrice: 197,
    category: 'E-commerce',
    emoji: '📦',
    gradient: 'from-green-900/60 to-emerald-900/60',
    badge: 'BESTSELLER',
    rating: 4.8,
    reviews: 3241,
    sales: 8924,
    features: ['Full video course', 'Store templates', 'Supplier list', 'Ad scripts', 'Lifetime access'],
    deliveryType: 'course',
  },
  {
    id: 'p3',
    title: 'Social Media Viral Template Pack',
    description: '200+ Canva templates for Instagram, TikTok & YouTube. Go viral in 24 hours.',
    price: 29,
    originalPrice: 69,
    category: 'Templates',
    emoji: '🎨',
    gradient: 'from-pink-900/60 to-rose-900/60',
    badge: 'NEW',
    rating: 4.7,
    reviews: 2108,
    sales: 21432,
    features: ['200+ templates', 'All platforms', 'Canva compatible', 'Custom fonts', 'Free updates'],
    deliveryType: 'instant',
  },
  {
    id: 'p4',
    title: 'SEO Domination Toolkit 2026',
    description: 'Rank #1 on Google with this complete SEO system. Includes 50 niche keyword lists.',
    price: 79,
    category: 'SEO',
    emoji: '🔍',
    gradient: 'from-orange-900/60 to-amber-900/60',
    rating: 4.9,
    reviews: 987,
    sales: 5621,
    features: ['50 keyword lists', 'Backlink outreach', 'Content templates', 'Rank tracker', 'Audit checklist'],
    deliveryType: 'instant',
  },
  {
    id: 'p5',
    title: 'Freelance Income Accelerator',
    description: 'Land $5k+ clients on Upwork and Fiverr. Proposal templates, pricing guides, and scripts.',
    price: 67,
    originalPrice: 127,
    category: 'Freelancing',
    emoji: '💼',
    gradient: 'from-purple-900/60 to-violet-900/60',
    badge: 'TRENDING',
    rating: 4.8,
    reviews: 1456,
    sales: 7832,
    features: ['50 proposal templates', 'Pricing calculator', 'Client scripts', 'Portfolio guide', 'Contracts'],
    deliveryType: 'instant',
  },
  {
    id: 'p6',
    title: 'Crypto Trading Signals Bot Setup',
    description: 'Set up your own crypto signal bot. Automated alerts for BTC, ETH & top altcoins.',
    price: 149,
    originalPrice: 299,
    category: 'Crypto',
    emoji: '₿',
    gradient: 'from-yellow-900/60 to-gold-900/60',
    rating: 4.6,
    reviews: 743,
    sales: 3291,
    features: ['Bot setup guide', '20 indicators', 'Alert templates', 'Risk management', 'Video walkthrough'],
    deliveryType: 'course',
  },
  {
    id: 'p7',
    title: 'Newsletter Monetization System',
    description: 'Build a 10k subscriber newsletter and monetize it for $3k+/mo. Full playbook.',
    price: 89,
    category: 'Newsletter',
    emoji: '📧',
    gradient: 'from-cyan-900/60 to-teal-900/60',
    rating: 4.9,
    reviews: 621,
    sales: 4123,
    features: ['Growth tactics', 'Monetization map', 'Email templates', 'Sponsor outreach', 'Automation flows'],
    deliveryType: 'course',
  },
  {
    id: 'p8',
    title: 'Print-on-Demand Empire Kit',
    description: 'Launch a profitable POD store on Etsy & Amazon. 500 ready-to-use designs included.',
    price: 59,
    originalPrice: 119,
    category: 'Print-on-Demand',
    emoji: '👕',
    gradient: 'from-red-900/60 to-rose-900/60',
    badge: 'HOT',
    rating: 4.7,
    reviews: 2834,
    sales: 15672,
    features: ['500 designs', 'Listing templates', 'Pricing guide', 'Platform walkthroughs', 'Niche research'],
    deliveryType: 'instant',
  },
  {
    id: 'p9',
    title: 'YouTube Automation Blueprint',
    description: 'Faceless YouTube channel that generates $2k+/mo with AI-generated content. Zero filming.',
    price: 127,
    originalPrice: 247,
    category: 'YouTube',
    emoji: '▶️',
    gradient: 'from-red-900/60 to-orange-900/60',
    badge: 'PREMIUM',
    rating: 4.9,
    reviews: 1893,
    sales: 9241,
    features: ['Channel setup', 'AI script tools', 'Niche selection', 'Monetization hacks', '1-on-1 call'],
    deliveryType: 'course',
  },
  {
    id: 'p10',
    title: 'Shopify Store Starter Templates',
    description: '20 premium Shopify themes optimized for conversion. Pre-built with winning products.',
    price: 44,
    category: 'Shopify',
    emoji: '🛒',
    gradient: 'from-green-900/60 to-lime-900/60',
    rating: 4.8,
    reviews: 1102,
    sales: 6832,
    features: ['20 themes', 'Winning products', 'Ad copy included', 'Mobile optimized', 'Free support'],
    deliveryType: 'instant',
  },
  {
    id: 'p11',
    title: 'Mindset & Wealth Psychology Guide',
    description: 'Reprogram your mind for wealth. The mental framework used by 7-figure earners.',
    price: 37,
    category: 'Mindset',
    emoji: '🧠',
    gradient: 'from-indigo-900/60 to-purple-900/60',
    rating: 4.7,
    reviews: 3421,
    sales: 28941,
    features: ['Ebook + Audio', 'Daily exercises', 'Affirmations pack', 'Journal templates', 'Bonus webinar'],
    deliveryType: 'instant',
  },
  {
    id: 'p12',
    title: 'Cold Email Domination System',
    description: 'Send 10,000 cold emails per month and land $5k+ clients. Tools, scripts & strategies.',
    price: 77,
    originalPrice: 147,
    category: 'Lead Gen',
    emoji: '📨',
    gradient: 'from-slate-900/60 to-gray-900/60',
    badge: 'POWERFUL',
    rating: 4.8,
    reviews: 891,
    sales: 5102,
    features: ['Email scripts', 'Tool stack guide', 'Lead scraping', 'Follow-up sequences', 'Legal compliance'],
    deliveryType: 'instant',
  },
];

export const MEMBERSHIP_TIERS = [
  {
    id: 'bronze',
    name: 'Bronze',
    price: 29,
    color: 'text-orange-600',
    bg: 'from-orange-900/30 to-orange-950/10',
    border: 'border-orange-700/30',
    emoji: '🥉',
    features: [
      'Access to 5 starter products',
      '10% affiliate commission',
      'Monthly newsletter',
      'Community Discord access',
      'Basic income tracker',
    ],
    popular: false,
  },
  {
    id: 'silver',
    name: 'Silver',
    price: 79,
    color: 'text-slate-300',
    bg: 'from-slate-700/30 to-slate-900/10',
    border: 'border-slate-600/30',
    emoji: '🥈',
    features: [
      'Access to 25 products',
      '25% affiliate commission',
      'Weekly income calls',
      'Priority support',
      'Advanced analytics dashboard',
      'Email marketing toolkit',
    ],
    popular: false,
  },
  {
    id: 'gold',
    name: 'Gold',
    price: 149,
    color: 'text-gold-400',
    bg: 'from-gold-900/30 to-amber-950/10',
    border: 'border-gold-600/30',
    emoji: '🥇',
    features: [
      'Full product library (100+ products)',
      '35% affiliate commission',
      'Daily live trading/income sessions',
      'Done-for-you funnels',
      'Custom store setup',
      '1-on-1 monthly coaching',
      'Early access to new products',
    ],
    popular: true,
  },
  {
    id: 'platinum',
    name: 'Platinum',
    price: 299,
    color: 'text-brand-300',
    bg: 'from-brand-900/40 to-brand-950/10',
    border: 'border-brand-600/30',
    emoji: '💎',
    features: [
      'Everything in Gold',
      '50% affiliate commission',
      'White-label resell rights',
      'Done-for-you business setup',
      'Weekly 1-on-1 coaching calls',
      'Private Platinum mastermind',
      'Revenue share opportunities',
      'VaultFlow partner badge',
    ],
    popular: false,
  },
];

export const TOOLS = [
  {
    id: 't1',
    name: 'Income Calculator',
    description: 'Project your monthly income across all 5 revenue streams based on your inputs.',
    icon: '🧮',
    category: 'Finance',
    free: true,
    color: 'text-green-400',
  },
  {
    id: 't2',
    name: 'Profit Margin Analyzer',
    description: 'Instantly calculate profit margins for any product or service you plan to sell.',
    icon: '📊',
    category: 'Finance',
    free: true,
    color: 'text-blue-400',
  },
  {
    id: 't3',
    name: 'Affiliate Link Manager',
    description: 'Create, track, and optimize all your affiliate links from one dashboard.',
    icon: '🔗',
    category: 'Affiliate',
    free: false,
    color: 'text-purple-400',
  },
  {
    id: 't4',
    name: 'Product Idea Generator',
    description: 'AI-powered tool that generates 10 profitable digital product ideas in seconds.',
    icon: '💡',
    category: 'AI',
    free: false,
    color: 'text-gold-400',
  },
  {
    id: 't5',
    name: 'Email Subject Line Tester',
    description: 'Score and optimize your email subject lines for maximum open rates.',
    icon: '📧',
    category: 'Email',
    free: true,
    color: 'text-pink-400',
  },
  {
    id: 't6',
    name: 'Price Optimizer',
    description: 'Find the perfect price point for your products using psychology-based pricing.',
    icon: '💰',
    category: 'Pricing',
    free: false,
    color: 'text-gold-400',
  },
];

export const TESTIMONIALS = [
  {
    name: 'Alex Rodriguez',
    handle: '@alexr_income',
    avatar: '👨‍💻',
    tier: 'Platinum',
    income: '$12,400/mo',
    text: 'VaultFlow changed everything. I was making $800/month at my job. Now I make $12k+ and work from Bali. The affiliate system alone pays my rent.',
    rating: 5,
  },
  {
    name: 'Sarah Kim',
    handle: '@sarahkim_digital',
    avatar: '👩‍💼',
    tier: 'Gold',
    income: '$6,200/mo',
    text: 'Bought the Dropshipping Blueprint and the AI Prompt Pack. Launched my store in 3 days. First sale in 48 hours. Now I\'m doing $6k per month passively.',
    rating: 5,
  },
  {
    name: 'Marcus Williams',
    handle: '@mw_financial',
    avatar: '👨‍🏫',
    tier: 'Gold',
    income: '$8,900/mo',
    text: 'The affiliate network is insane. I promote VaultFlow products to my newsletter and earn 35% on everything. Set it up once, get paid forever.',
    rating: 5,
  },
  {
    name: 'Emma Thompson',
    handle: '@emmatcreates',
    avatar: '👩‍🎨',
    tier: 'Silver',
    income: '$3,100/mo',
    text: 'As a graphic designer, the template packs saved me 40 hours/week. I now sell MY templates on VaultFlow and earn $3k/mo on top of my freelance work.',
    rating: 5,
  },
  {
    name: 'James Park',
    handle: '@jpark_crypto',
    avatar: '🧑‍💻',
    tier: 'Platinum',
    income: '$18,000/mo',
    text: 'Combined the crypto toolkit with the YouTube automation blueprint. Grew my channel to 50k subscribers, monetized it, and now pull $18k a month. Unreal.',
    rating: 5,
  },
  {
    name: 'Diana Santos',
    handle: '@dianasantos_biz',
    avatar: '👩‍🚀',
    tier: 'Gold',
    income: '$4,700/mo',
    text: 'The membership is worth every penny. The weekly coaching calls and done-for-you funnels helped me hit $4,700/mo within 90 days of joining.',
    rating: 5,
  },
];

export function generateRevenueData() {
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  let base = 1200;
  return months.map((month, i) => {
    const growth = 1 + (i * 0.18) + (Math.random() * 0.12);
    const value = Math.round(base * growth);
    return {
      month,
      products: Math.round(value * 0.35),
      membership: Math.round(value * 0.28),
      affiliate: Math.round(value * 0.22),
      tools: Math.round(value * 0.15),
      total: value,
    };
  });
}
