'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Play, DollarSign, TrendingUp, Users, Zap } from 'lucide-react';

function LiveCounter({ target, prefix = '' }: { target: number; prefix?: string }) {
  const [count, setCount] = useState(0);
  useEffect(() => {
    const duration = 2500;
    const steps = 80;
    const increment = target / steps;
    let current = 0;
    const timer = setInterval(() => {
      current += increment;
      if (current >= target) { setCount(target); clearInterval(timer); }
      else { setCount(Math.floor(current)); }
    }, duration / steps);
    return () => clearInterval(timer);
  }, [target]);
  return <span>{prefix}{count.toLocaleString()}</span>;
}

export function HeroSection() {
  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden bg-grid">
      {/* Background orbs */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-brand-700/20 rounded-full blur-[120px] animate-pulse-slow" />
      <div className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-gold-500/10 rounded-full blur-[100px] animate-pulse-slow" />
      <div className="absolute top-1/2 left-1/2 w-64 h-64 bg-brand-600/10 rounded-full blur-[80px]" />

      <div className="relative z-10 max-w-6xl mx-auto px-4 text-center pt-20">
        {/* Badge */}
        <div className="inline-flex items-center gap-2 glass rounded-full px-4 py-2 mb-8 border border-gold-500/30">
          <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse" />
          <span className="text-sm text-white/70">
            <span className="text-gold-400 font-semibold">$2.4M+</span> generated by our community this month
          </span>
        </div>

        {/* Headline */}
        <h1 className="text-5xl md:text-7xl font-black mb-6 leading-tight tracking-tight">
          <span className="text-white">Your </span>
          <span className="shimmer-text text-glow">24/7 Income</span>
          <br />
          <span className="text-white">Machine is </span>
          <span className="text-brand-400">Live</span>
        </h1>

        <p className="text-xl md:text-2xl text-white/60 max-w-3xl mx-auto mb-10 leading-relaxed">
          VaultFlow powers <strong className="text-white">5 revenue streams</strong> simultaneously —
          digital products, memberships, affiliate commissions, SaaS tools, and content monetization.
          Fully automated. Always growing.
        </p>

        {/* CTAs */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
          <Link
            href="/dashboard"
            className="group flex items-center gap-2 px-8 py-4 bg-gold-gradient rounded-2xl text-black font-black text-lg hover:opacity-90 transition-all glow-gold"
          >
            <Zap size={20} className="fill-black" />
            Launch Your Income
            <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />
          </Link>
          <Link
            href="/store"
            className="flex items-center gap-2 px-8 py-4 glass rounded-2xl text-white font-bold text-lg hover:bg-white/10 transition-all border border-white/10"
          >
            <Play size={18} />
            Explore Products
          </Link>
        </div>

        {/* Live stats row */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto">
          {[
            { icon: DollarSign,  label: 'Total Paid Out',    value: 2847293, prefix: '$', color: 'text-gold-400' },
            { icon: Users,       label: 'Active Members',    value: 14892,   prefix: '',  color: 'text-brand-400' },
            { icon: TrendingUp,  label: 'Avg Monthly Earn',  value: 3847,    prefix: '$', color: 'text-green-400' },
            { icon: Zap,         label: 'Products Sold',     value: 98241,   prefix: '',  color: 'text-gold-400' },
          ].map(({ icon: Icon, label, value, prefix, color }) => (
            <div key={label} className="glass rounded-2xl p-5 text-center border border-white/5 hover:border-brand-700/50 transition-all">
              <Icon size={22} className={`${color} mx-auto mb-2`} />
              <div className={`text-2xl font-black ${color} animate-count-up`}>
                <LiveCounter target={value} prefix={prefix} />
              </div>
              <div className="text-xs text-white/40 mt-1">{label}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Scroll indicator */}
      <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 text-white/30">
        <span className="text-xs">Scroll to explore</span>
        <div className="w-0.5 h-8 bg-gradient-to-b from-white/30 to-transparent animate-pulse" />
      </div>
    </section>
  );
}
